### ISSUE TITLE
Main Content Is Not Centered Properly

### ISSUE THREAD

**Issue by ejimeneztech** [ejimeneztech/portfolioWebsite#3]
The main content should be centered and have a background image similar to this https://codepen.io/freeCodeCamp/full/YqLyXB

**Comment by oceanerousseeuw** [comment]
Hello !

I'm experiment in CSS language and I want to help you for this issue
It's my first contribution. Can I work on this issue?
If there are problem in my contribution, can you tell me for improve myself ?

Have a nice day :)

**Comment by ejimeneztech** [comment]
Hi there!

Sorry for the late reply. I would definitely appreciate some help. 

Please feel free to work on this issue and let me know if you have any other questions!

Thanks!

**Comment by ejimeneztech** [comment]
Hello Again, 

I had some time to work on this today. I think I might have solved this issue.  I changed a few things in the 'body' element of the css file. Code is below:
body {
    margin: 0;
    padding-left: 40px;
    padding-right: 40px;
    background-color: grey;
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size: 20px;
    
}

I'll be closing this for now. However, I would still be interested in any feedback you might have. 

Thanks!
